/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quant_sdk_Device */

#ifndef _Included_com_quant_sdk_Device
#define _Included_com_quant_sdk_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quant_sdk_Device
 * Method:    GetDevInfoNav
 * Signature: (Lcom/quant/sdk/RDevInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_quant_sdk_Device_GetDevInfoNav
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
